name: digital_sky
description: A monorepo for cloud security demo game.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  melos: ^5.3.0
  test: ^1.24.0
