name: digital_sky_common
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_generator: ^2.4.0
  signalr_netcore: ^1.3.7
  riverpod_annotation: ^2.3.5
  uuid: ^3.0.7
  localstorage: ^5.0.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.0
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.0
