name: digital_sky_master
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  digital_sky_common:
    path: ../../packages/digital_sky_common
  flutter_riverpod: ^2.5.1
  localstorage: ^5.0.0
  riverpod_annotation: ^2.3.5
  riverpod: ^2.5.1
  freezed: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
